<a href="https://colab.research.google.com/github/niedakaito/EU_M_Math/blob/main/Chap02_2_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-1-3 この章で使うライブラリのインポート

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第3位まで表示という意味
%precision 3

'%.3f'

# 2-2-2 配列操作

In [ ]:
# 配列の作成
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
display(data)
print('\n')


# データの型
display(data.dtype)
print('\n')


print('次元数：', data.ndim)
print('要素数：', data.size)
print('\n')


# それぞれの数字を係数倍
display(data*2)
print('\n')


print('掛け算：', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
print('累乗：', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) ** 2)
print('割り算：', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) / np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
print('\n')


# 現在の値を表示
print('そのまま：', data)
# ソートした結果を表示
data.sort()
print('ソート後：', data)
print('\n')


data[::-1].sort()
print('ソート後：', data)
print('\n')


# 最小値
print('Min：', data.min())
# 最大値
print('Max：', data.max())
# 合計
print('Sum：', data.sum())
# 積み上げ
print('Cum：', data.cumsum())
# 積み上げ割合
print('Ratio：', data.cumsum() / data.sum())
print('\n')


random.seed(0)
# 正規分布（平均0、分散1）の乱数を10個発生
rnd_data = random.randn(10)
print('乱数10個の配列：', rnd_data)
print('\n')


# ランダム抽出
print('10個を抽出（重複有、復元抽出）:', random.choice(data, 10))
print('10個を抽出（重複無、非復元抽出）：', random.choice(data, 10, replace = False))
print('\n')


# Nは乱数の発生数、10の6乗
N = 10**6
print('\n')


# Python版（以下のrange(N)は0からN-1までの整数を用意しています。
# 「_」は代入した値を参照しないときに使う慣例的な変数名です。
# 例えば、for a in range(N)ト書くのと同じですが、aと書くと、
# そのあとでを後で使うように見えるので、その値を参照しないときは、
# for _ in range(N)のように慣例的に書く書き方です。
normal_data = [random.random() for _ in range(N)]

# Numpy版
numpy_random_data = np.array(normal_data)

# calc time : 合計値
# 普通の処理
%timeit sum(normal_data)

# Numpyを使った処理
%timeit np.sum(numpy_random_data)
print('\n')


print('連続した整数（0-8）:', np.arange(9))
print('\n')


array1 = np.arange(9).reshape(3, 3)
print(array1)
print('\n')

print('1行目:', array1[0, :])
print('1列目：', array1[:, 0])
print('\n')

array2 = np.arange(9, 18).reshape(3,3)
print(array2)
print('\n')


print('行列の積：', np.dot(array1, array2))
print('要素同士の積：', array1 * array2)
print('\n')


print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.int64))

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

dtype('int64')



次元数： 1
要素数： 10




array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])



掛け算： [10 18 24 28 30 30 28 24 18 10]
累乗： [  1   4   9  16  25  36  49  64  81 100]
割り算： [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


そのまま： [ 9  2  3  4 10  6  7  8  1  5]
ソート後： [ 1  2  3  4  5  6  7  8  9 10]


ソート後： [10  9  8  7  6  5  4  3  2  1]


Min： 1
Max： 10
Sum： 55
Cum： [10 19 27 34 40 45 49 52 54 55]
Ratio： [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


乱数10個の配列： [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


10個を抽出（重複有、復元抽出）: [4 3 3 2 9 5 1 2 1 6]
10個を抽出（重複無、非復元抽出）： [ 6  9  4  3  8  2  5  1 10  7]




7.48 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
362 µs ± 7.93 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


連続した整数（0-8）: [0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


1行目: [0 1 2]
1列目： [0 3 6]


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


行列の積： [[ 42  45  48]
 [150 162 174]
 [258 279 300]]
要素同士の積： [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


[[0 0 0]
 [0 0 0]]
[[1