<a href="https://colab.research.google.com/github/niedakaito/EU_M_Math/blob/main/Chap05_Ex_13_14_ipynb_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

from scipy import interpolate

# 練習問題 5-13

In [2]:
B = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
B

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
U, s, Vs, = sp.linalg.svd(B)
m, n = B.shape

S = sp.linalg.diagsvd(s, m, n)

print('U.S.V* = \n', U@S@Vs)

U.S.V* = 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


# 練習問題 5-14

In [5]:
A = np.identity(3)
print(A)
A[0,:] = 1
A[:,0] = 1
A[0,0] = 3
b = np.ones(3)
print(A)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[1. 1. 1.]


In [7]:
(LU,piv) = sp.linalg.lu_factor(A)

L = np.identity(3) + np.tril(LU, -1)
U = np.triu(LU)
P = np.identity(3)[piv]

x = sp.linalg.lu_solve((LU,piv), b)
x

array([-1.,  2.,  2.])