<a href="https://colab.research.google.com/github/niedakaito/EU_M_Math/blob/main/Chap05_Ex_07_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

# 練習問題 5-7

In [2]:
# データの準備
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

In [3]:
np.hstack((sample_array1, sample_array2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

# 練習問題 5-8

In [4]:
np.vstack((sample_array1, sample_array2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 練習問題 5-9

In [5]:
sample_list = [1,2,3,4,5]
print(sample_list)

[1, 2, 3, 4, 5]


In [6]:
np.array(sample_list) + 3

array([4, 5, 6, 7, 8])