<a href="https://colab.research.google.com/github/niedakaito/EU_M_Math/blob/main/Chap02_3_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-3 Scipyの基礎

In [4]:
import numpy as np
%precision 3


# 線形代数用のライブラリ
import scipy.linalg as linalg

# 最適化計算（最小値）用の関数
from scipy.optimize import minimize_scalar


matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print('行列式')
print(linalg.det(matrix))
print('\n')

# 逆行列
print('逆行列')
print(linalg.inv(matrix))
print('\n')


# 固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)

# 固有値と固有ベクトル
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)
print('\n')


# 関数の定義
def my_functiom(x):
  return (x**2 + 2*x + 1)

# ニュートン法の読み込み
from scipy.optimize import newton

# 計算実行
print(newton(my_functiom,0))
print('\n')


# 計算の実行
print(minimize_scalar(my_functiom, method = 'Brent'))

行列式
-4.0


逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


-0.9999999852953906


 message: 
          Optimization terminated successfully;
          The returned value satisfies the termination criteria
          (using xtol = 1.48e-08 )
 success: True
     fun: 0.0
       x: -1.0000000000000002
     nit: 4
    nfev: 8
