<a href="https://colab.research.google.com/github/niedakaito/EU_M_Math/blob/main/Chap02_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 新しいセクション

# 新しいセクション

In [ ]:
%precision 3


import numpy as np

# 配列の作成
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
# data


# データの型
# data.dtype


# print('次元数：', data.ndim)
# print('要素数：', data.size)


# それぞれの数字を係数倍
# data*2


# print('掛け算：', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) * np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))
# print('累乗：', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) ** 2)
# print('割り算：', np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) / np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))


# 現在の値を表示
# print('そのまま：', data)
# ソートした結果を表示
# data.sort()
# print('ソート後：', data)


# data[::-1].sort()
# print('ソート後：', data)


# 最小値
# print('Min：', data.min())
# 最大値
# print('Max：', data.max())
# 合計
# print('Sum：', data.sum())
# 積み上げ
# print('Cum：', data.cumsum())
# 積み上げ割合
# print('Ratio：', data.cumsum() / data.sum())


import numpy.random as random
random.seed(0)
# 正規分布（平均0、分散1）の乱数を10個発生
# rnd_data = random.randn(10)
# print('乱数10個の配列：', rnd_data)


# ランダム抽出
# 10個を抽出（重複有、復元抽出）
# print(random.choice(data, 10))

# 10個を抽出（重複無、非復元抽出）
# print(random.choice(data, 10, replace = False))


# Nは乱数の発生数、10の6乗
N = 10**6

# Python版（以下のrange(N)は0からN-1までの整数を用意しています。
# 「_」は代入した値を参照しないときに使う慣例的な変数名です。
# 例えば、for a in range(N)ト書くのと同じですが、aと書くと、
# そのあとでを後で使うように見えるので、その値を参照しないときは、
# for _ in range(N)のように慣例的に書く書き方です。
# normal_data = [random.random() for _ in range(N)]

# Numpy版
# numpy_random_data = np.array(normal_data)

# calc time : 合計
# 普通の処理
# %timeit sum(normal_data)

# Numpyを使った処理
# %timeit np.sum(numpy_random_data)


# np.arange(9)

array1 = np.arange(9).reshape(3, 3)
# print(array1)

# 1行目
# array1[0, :]

# 1列目
# array1[:, 0]


array2 = np.arange(9, 18).reshape(3,3)
# print(array2)

# 行列の積
# np.dot(array1, array2)

# 要素同士の積
# array1 * array2

print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.int64))

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
